### ISSUE TITLE
no respond from cloud key

### ISSUE THREAD

**Issue by MarpleA** [gregcube/unifi-mimic#1]
Hi,

i ran `/unifi-mimic -D -i enp3s0` on a machine which is on the same subnet as the unifi cloud key. Cloud key is pingable.

But unfortunately there aren't any responses nor files being created. Any idea what's wrong?

EDIT: on cloudkey "Make this Network application discoverable on the Layer 2 network." is enabled

EDIT2: I figured it out. UFW on the machine I did the testing blocked incoming traffic.

Does work now. Thanks for this awesome tool!

**Comment by gregcube** [comment]
Awesome!  Glad to hear it's working.
