### ISSUE TITLE
connecting via VPN possible?

### ISSUE THREAD

**Issue by MarpleA** [gregcube/unifi-mimic#2]
as mentioned in the other issue I opened, it does work from subnet to subnet.
However, I tried to connect the protect app to my unifi controller via a wireguard vpn. 
Mobile (outside of network) -> Wireguard Server -> Unifi Controller

my wireguard server and the unifi controller are in different subnets as well but using this solution doesn't work with this setup. 
Could it be, that the proxy doesn't work in that case since the wireguard server is actually trying to connect to the unifi controller instead of the mobile directly?

**Comment by gregcube** [comment]
Yeah, in my testing I found that if I'm on a wifi network (public, bar or a friend's house for example) and connect to my wireguard server (it's on a different subnet, too) it works.  But it doesn't seem to work over mobile connection/data when connected to wireguard.  Not sure why and haven't had much time to debug.

**Comment by jirkapas** [comment]
The app has a check in it that stops the device discovery process when you aren't connected to wifi so it will never work over mobile data with the stock app.

**Comment by gregcube** [comment]
> The app has a check in it stops the device discovery process when you aren't connected to wifi so it will never work over data with the stock app.

Ah, that explains it.  Too bad.

**Comment by MarpleA** [comment]
good to know. seems like unifi tries hard to push us to their cloud service. :-|

**Comment by jirkapas** [comment]
The latest update on Android and iPhones removed the wifi check so local connection now works over a VPN 🥳. However I wasn't able to get unifi-mimic working but it works with a OPNsense plugin called UDP Broadcast Relay.
