### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by sborn** [gregcube/unifi-mimic#3]
Hi. I followed all of your instructions. It produced the payload files for the 40 devices we have. It produced two for each UNVR. The old UNVR is mimicked by the old Unifi-Proxy, and I was trying to set up the new one using this cleaner version.

Running:
`sudo ./unifi-mimic -L -p 192.168.1.17 -i wlan0 -f`
and
`sudo ./unifi-mimic -L -p 192.168.1.17-1 -i wlan0 -f`

on 192.168.10.53

Gets me:
Listening on 233.89.188.1:10001

Is that supposed to be listening on 192.168.10.53?

On the iPads on 192.168.10.XX, the old UNVR (192.168.1.16) is showing up, but not the new UNVR (192.168.1.17)

**Comment by gregcube** [comment]
233.89.188.1 is the multicast IP address it uses.

When you say, "showing up" - do you mean you can't see the UNVR at all? - or you can see it, but the app doesn't say it's connected locally?

Does it work for your old UNVR, if you replace unifi-proxy?

**Comment by sborn** [comment]
Can’t see it at all. We are closed because of weather today, so I won’t be in to check things. I didn’t think of shutting down the other unifi-proxy services and trying Unifi-mimic for 192.168.1.16 (I have it running for 192.168.1.16 on 10 different Pis because I clone the image and they all have it now), but I can do that during lunch tomorrow. Thanks for the quick response.

**Comment by sborn** [comment]
> Does it work for your old UNVR, if you replace unifi-proxy?

Tested today. It does not.

**Comment by sborn** [comment]
> When you say, "showing up" - do you mean you can't see the UNVR at all? - or you can see it, but the app doesn't say it's connected locally?

I should make clear that the account I am using on devices are local-only accounts.

**Comment by gregcube** [comment]
Well that sucks, not sure why it doesn't work for you.  When I have some spare time I'll add some debug/ verbosity output - perhaps that'll help identify where it's failing.

Are you using an iphone or android?

**Comment by sborn** [comment]
IPads and iPhones. We’ve got a bunch, so it isn’t a single device.

**Comment by jirkapas** [comment]
> It produced the payload files for the 40 devices we have. It produced two for each UNVR.
> 
> Running: `sudo ./unifi-mimic -L -p 192.168.1.17 -i wlan0 -f` and `sudo ./unifi-mimic -L -p 192.168.1.17-1 -i wlan0 -f`

I also get two response files for my UNVR but I always run unifi-mimic with the first file without the -1 at the end and everything works so far. Have you tried running mimic only with one of the response files?

**Comment by sborn** [comment]
> Have you tried running mimic only with one of the response files?

Yes. I tried a lot of permutations. I tried the single one first. 

I created a service for unify-proxy for both, so I’m okay for now. But I’d still like to get this figured out because it is so much cleaner 🙂
